bilibili:
  bili_jct: 118d1052b6cddf1cafc1294845e226ae
  buvid3: null
  login_uid: 3546766915930803
  sessdata: f31f9a1b%2C1798018988%2C303b9%2A62CjBvq1Xzr_FaRsznZO2w274_65sspuhdDgIqSTUHX8n2DzDX4NXrucQ57-lIA_QNDboSVjZyYmNsU0JpdThWcWZNTWp6NGxDRXBhaWpFTkpka0ZmenpJNUFiVl9lNlFxNnNSaXZLbjhjcjBVT2RlbU1WLUZPSmZQdzVGU2J2ZlZIUTVxYW51WU5nIIEC
livehelper:
  credential_file: bilibili.json
  enabled: true
  force_qr_login: false
  interval_jitter_seconds: 10
  interval_seconds: 60
  quotes:
  - 晚上好呀~
  - 主播今天状态不错
  - '666'
  - 来了来了
  - 加油加油
  room_id: '1758153368'
  skip_duplicate: true
logging:
  level: INFO
network:
  browser_headers:
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
      like Gecko) Chrome/120.0.0.0 Safari/537.36
