bilibili:
  bili_jct: 
  buvid3: 
  login_uid: 
  sessdata: 
livehelper:
  credential_file: bilibili.json
  enabled: true
  force_qr_login: false
  interval_jitter_seconds: 10
  interval_seconds: 60
  quotes:
  - 晚上好呀~
  - 主播今天状态不错
  - '666'
  - 来了来了
  - 加油加油
  room_id: ''
  skip_duplicate: true
logging:
  level: INFO
network:
  browser_headers:
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
      like Gecko) Chrome/120.0.0.0 Safari/537.36
